@IdentityService_HostAddress = http://localhost:5274

POST {{IdentityService_HostAddress}}/api/auth/register
BODY: {     
  "username": "admin",
  "password": "Admin@123",
  "email": "admin@gmail.com"
}
Accept: application/json

###
